### ISSUE TITLE
Node name prefix

### ISSUE THREAD

**Issue by mrcsilva** [rancher-plugins/rancher-machine-driver-oci#12]
Is there any particular reason the node driver has a defaultNodeNamePfx for each node?

Thanks!

**Comment by jlamillan** [comment]
I don't believe there was a functional reason for it, no. The prefix was more about making it easier to identify which instances were created by the docker-machine.

**Comment by jlamillan** [comment]
Node name prefix removed in version `v1.2.0`

**Comment by mrcsilva** [comment]
Oh, got it. However, I think Rancher already assigns a name to the machine based on the node pool name.

Thank you for the quick fix!
