### ISSUE TITLE
Add support for flexible compute shapes by setting oCPUs

### ISSUE THREAD

**Issue by jlamillan** [rancher-plugins/rancher-machine-driver-oci#7]
We need to add support for flexible shapes by allowing the user to specify the number of oCPUs when a flexible node-shape is specified e.g.

`--oci-node-shape VM.Standard.E3.Flex  --flex-ocpus = 12`

**Comment by MiguelLucas** [comment]
Is it possible to use this while it is not yet integrated in Rancher UI? If yes, how can I do it?

**Comment by MiguelLucas** [comment]
Ended up forking this and passing my desired values by default to the createInstance call 👍

**Comment by braunsonm** [comment]
It would be great if burstable/baseline performance would also be supported with the Flex shape

**Comment by jlamillan** [comment]
@braunsonm 

that's a great idea. 

See: https://github.com/rancher-plugins/rancher-machine-driver-oci/issues/11

**Comment by jlamillan** [comment]
Filed a new issue to support setting burstable option on Flex shapes #11 

Closing this issue since support for setting oCPUs on flex shapes has been merged.
